export const REQUEST_BEERS = 'DASHBOARD/REQUEST_BEERS';
export const RECEIVE_BEERS = 'DASHBOARD/RECEIVE_BEERS';
export const INVALIDATE_REQUEST_BEERS = 'DASHBOARD/INVALIDATE_REQUEST_BEERS';

export const SEARCH_REQUEST_BEERS = 'DASHBOARD/SEARCH_REQUEST_BEERS';
export const SEARCH_RECEIVE_BEERS = 'DASHBOARD/SEARCH_RECEIVE_BEERS';
export const INVALIDATE_SEARCH_BEERS = 'DASHBOARD/INVALIDATE_SEARCH_BEERS';

export const FILTER_BEERS = 'DASHBOARD/FILTER_BEERS';


