export const CLEAN_BEER = 'BEER/CLEAN_BEER';

export const REQUEST_BEER = 'BEER/REQUEST_BEER';
export const RECEIVE_BEER = 'BEER/RECEIVE_BEER';
export const INVALIDATE_REQUEST_BEER = 'BEER/INVALIDATE_REQUEST_BEER';


