export const REQUEST_BEER = 'BEER/REQUEST_BEER';
export const RECEIVE_BEER = 'BEER/RECEIVE_BEER';
export const INVALIDATE_REQUEST_BEER = 'BEER/INVALIDATE_REQUEST_BEER';

export const RECEIVE_ERROR = 'COMMON/RECEIVE_ERROR';

export const REQUEST_BEERS = 'DASHBOARD/REQUEST_BEERS';
export const RECEIVE_BEERS = 'DASHBOARD/RECEIVE_BEERS';
export const INVALIDATE_REQUEST_BEERS = 'DASHBOARD/INVALIDATE_REQUEST_BEERS';

export const SEARCH_REQUEST_BEERS = 'DASHBOARD/SEARCH_REQUEST_BEERS';
export const SEARCH_RECEIVE_BEERS = 'DASHBOARD/SEARCH_RECEIVE_BEERS';
export const INVALIDATE_SEARCH_BEERS = 'DASHBOARD/INVALIDATE_SEARCH_BEERS';

export const ADD_TO_FAVORITES = 'FAVORITES/ADD_TO_FAVORITES';
export const REQUEST_FAVORITES = 'FAVORITES/REQUEST_FAVORITES';
export const RECEIVE_FAVORITES = 'FAVORITES/RECEIVE_FAVORITES';
export const INVALIDATE_REQUEST_FAVORITES = 'FAVORITES/INVALIDATE_REQUEST_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'FAVORITES/REMOVE_FROM_FAVORITES';

export const GET_FAVORITES = 'FAVORITES/GET_FAVORITES';

export const SET_ALCOHOL = 'FILTER/SET_ALCOHOL';
export const SET_BITTERNESS = 'FILTER/SET_BETTERNESS';
export const SET_COLOR = 'FILTER/SET_COLOR';
export const SET_NAME = 'FILTER/SET_NAME';

export const TOGGLE_VISIBILITY_SIDEBAR = 'SIDEBAR/SHOW_VISIBILITY_SIDEBAR';

