export const ADD_TO_FAVORITES = 'FAVORITES/ADD_TO_FAVORITES';
export const REQUEST_FAVORITES = 'FAVORITES/REQUEST_FAVORITES';
export const RECEIVE_FAVORITES = 'FAVORITES/RECEIVE_FAVORITES';
export const INVALIDATE_REQUEST_FAVORITES = 'FAVORITES/INVALIDATE_REQUEST_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'FAVORITES/REMOVE_FROM_FAVORITES';

export const GET_FAVORITES = 'FAVORITES/GET_FAVORITES';
