export const ADD_TO_FAVORITES = 'FAVORITES/ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'FAVORITES/REMOVE_FROM_FAVORITES';
export const CONTAINS_IN_FAVORITES = 'FAVORITES/CONTAINS_IN_FAVORITES';